insert into clients(name, surname, passport_nr)values ('Joe', 'Biden', 'AA854G51');
insert into clients(name, surname, passport_nr)values ('Doland', 'Duck', 'DFG581515');
insert into clients(name, surname, passport_nr)values ('Pit', 'Schubert', 'DE785210');
insert into clients(name, surname, passport_nr)values ('Mark', 'Willow', 'ET525QA4');
insert into clients(name, surname, passport_nr)values ('Andy', 'Kirkpatrick', 'EL561CAP');
insert into clients(name, surname, passport_nr)values ('Kazimierz', 'Trop', 'N601R100');
insert into guides (name) values ('Nowakowski');
insert into guides (name) values ('Zdzalik');
insert into guides (name) values ('KowalGuide');
insert into guides (name) values ('BestGuide');
insert into destinations (name)values ('Berchtesgaden');
insert into destinations (name)values ('Cangas de Onis');
insert into destinations (name)values ('Spiska Bela');
insert into destinations (name)values ('Vladikavkaz');
insert into destinations (name)values ('Minsk');
insert into trips (id_destination, departure_date, return_date, suggested_price, id_guide)values (1, '2021-05-01', '2021-05-12', 2000, 1);
insert into trips (id_destination, departure_date, return_date, suggested_price, id_guide)values (2, '2021-06-01', '2021-06-12', 2300, 2);
insert into trips (id_destination, departure_date, return_date, suggested_price, id_guide)values (3, '2020-07-01', '2020-07-12', 1199.99, 3);
insert into trips (id_destination, departure_date, return_date, suggested_price, id_guide)values (4, '2019-08-01', '2019-08-12', 4000, 2);
insert into trips (id_destination, departure_date, return_date, suggested_price, id_guide)values (5, '2020-09-04', '2020-09-11', 1199.99, 4);
insert into reservations(id_client, id_trip, actual_price)values (1,2,2000);
insert into reservations(id_client, id_trip, actual_price)values (2,4, 4000);
insert into reservations(id_client, id_trip, actual_price)values (3,1, 2000);
insert into reservations(id_client, id_trip, actual_price)values (3,2, 2250);
insert into reservations(id_client, id_trip, actual_price)values (3,5, 1100);
insert into reservations(id_client, id_trip, actual_price)values (4,1, 2000);
insert into reservations(id_client, id_trip, actual_price)values (5,3, 1199.99);
insert into reservations(id_client, id_trip, actual_price)values (6,2, 2300);
insert into reservations(id_client, id_trip, actual_price)values (6,1, 1900);