insert into guides (name) values ('Nowakowski');
insert into guides (name) values ('Zdzalik');
insert into guides (name) values ('KowalGuide');
insert into guides (name) values ('BestGuide');
insert into destinations (name)values ('Berchtesgaden');
insert into destinations (name)values ('Cangas de Onis');
insert into destinations (name)values ('Spiska Bela');
insert into destinations (name)values ('Vladikavkaz');
insert into destinations (name)values ('Minsk');
insert into clients(name, surname, passport_nr)values ('Joe', 'Biden', 'rety');
insert into clients(name, surname, passport_nr)values ('Doland', 'Duck', 'ghj');
insert into clients(name, surname, passport_nr)values ('Pit', 'Schubert', 'kloio');
insert into clients(name, surname, passport_nr)values ('Mark', 'Willow', 'cvbfg');
insert into clients(name, surname, passport_nr)values ('Andy', 'Kirkpatrick', 'azazaza');
insert into clients(name, surname, passport_nr)values ('Jadwiga', 'Trop', 'qaqaqaqaq');